version: '3.4'

services:
    php-74:
        container_name: php-74
        image: php74:local
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/app
